spring.application.name=TarrifBuilder
server.port=8000
# server.address=10.10.19.29
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
 
 
server.servlet.session.timeout=15m

login.datasource.jdbc-url=jdbc:oracle:thin:@192.168.149.121:1521/ATTTEST
login.datasource.username=FTT_MSPTUNE_DEV
login.datasource.password=FTT_MSPTUNE_DEV
login.datasource.driver-class-name=oracle.jdbc.OracleDriver
login.datasource.hikari.minimum-idle=5
login.datasource.hikari.maximum-pool-size=5
login.datasource.hikari.idle-timeout=5000
login.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
login.datasource.connectionProperties=oracle.jdbc.defaultNChar=true;charSet=ISO_1